// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "products",
    columns: [
      { name: "link", type: "string", unique: true },
      {
        name: "pictures",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
      { name: "subject", type: "string" },
      { name: "subCategory", type: "string" },
      { name: "product", type: "string" },
      { name: "review", type: "string" },
      { name: "author", type: "string" },
      { name: "category", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Products = InferredTypes["products"];
export type ProductsRecord = Products & XataRecord;

export type DatabaseSchema = {
  products: ProductsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Kyle-Kelley-s-workspace-8qp0rn.us-east-1.xata.sh/db/creatureViews",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
